jobs6.yml

diff --git a/.github/workflows/jobs.yml b/.github/workflows/jobs.yml
--- a/.github/workflows/jobs.yml
+++ b/.github/workflows/jobs.yml
@@ -38,11 +38,17 @@ jobs:
         # Use sqlcmd to perform the backup on the SQL Server instance
         sqlcmd -S tcp:34.131.69.65,1433 -U ${SQL_USERNAME} -P ${SQL_PASSWORD} -Q "BACKUP DATABASE [surya] TO DISK = N'/tmp/$BACKUP_NAME' WITH INIT, COMPRESSION"
         
-        echo "Backup created at /tmp/$BACKUP_NAME"
-        
-        # Upload the backup file to Google Cloud Storage
-        gsutil cp /tmp/$BACKUP_NAME gs://kadali/localbackup/$BACKUP_NAME
-        echo "Backup uploaded to gs://kadali/localbackup/$BACKUP_NAME"
+        # Check if the backup file exists
+        if [ -f "/tmp/$BACKUP_NAME" ]; then
+          echo "Backup created successfully at /tmp/$BACKUP_NAME"
+          
+          # Upload the backup file to Google Cloud Storage
+          gsutil cp /tmp/$BACKUP_NAME gs://kadali/localbackup/$BACKUP_NAME
+          echo "Backup uploaded to gs://kadali/localbackup/$BACKUP_NAME"
+        else
+          echo "Backup failed! No backup file created."
+          exit 1
+        fi
 
     # Step 5: Verify the backup file in GCS (Optional)
     - name: Verify Backup in GCS
